highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://TomatoZuo.github.io
author: tomatoz

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: tomatoz's blog
name: Chris Turner
email: christurner@me.com
email_full: mailto:youremail@me.com
website: github.io
website_full: https://TomatoZuo.github.io
github: trending
twitter: 
tel: 
tel_full: 
google_maps: 'https://TomatoZuo.github.io'
address:
  street: 44 Perth Street
  postcode: EH3 5BL
  city: Edinburgh
  country: United Kingdom
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
